### ISSUE TITLE
As a Developer, I want to learn more about different authentication providers, to be able to make an informed decision about which one to implement for the Chirp! webapp.

### ISSUE THREAD

**Issue by lrtzndrsn** [ITU-BDSA23-GROUP9/Chirp#121]
Acceptance criteria: 

- Every Developer in the team has read about:
      - ASP.NET Core Identity 
      - Azure AD B2C w/ Github (Entra ID)
      - Azure Web Apps Easy Auth 
 - We have the required knowledge to make an informed decision about which platform to use. 
 
Co-authored by:
@ClaraWJ 
@AntonFriis 
@olinesk 
@JKramer91 
@JohanSandager

**Comment by JohanSandager** [comment]
We have chosen to use ASP.NET Core Identity because:
- Built-in
- Includes APIs, UI and backend db configurations
- Support external logins (Google, Facebook etc.)
- Good for SPA (Single Page Applications)
- Allows for both Authorization and Authentication 
- More control of the code and functionality 
Cons to be aware of:
- We store the data ourselves (GDPR & persistency)
- More code and more complexity (problem in regards to maintainability) 

We also considered Easy Auth, but it lacked some of the key features of Core Identity such as authorization.
